-- Esquema sintético mínimo para la suite global en PostgreSQL desechable.
-- Sin datos de Neon ni credenciales. No ejecutar en una base persistente.

CREATE TABLE predicciones_registradas (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    partido_id uuid,
    temporada_id uuid,
    competicion_id uuid,
    equipo_local_id uuid,
    equipo_visitante_id uuid,
    mercado text,
    origen text,
    fecha_partido date,
    tipo_partido text,
    modelo_version_id integer,
    linea numeric,
    linea_es_sintetica boolean,
    lado text,
    media_predicha numeric,
    desviacion_predicha numeric,
    p_raw numeric,
    p_calibrada numeric,
    calibrador_id uuid,
    calibrador_id_efectivo uuid GENERATED ALWAYS AS
        (COALESCE(calibrador_id, '00000000-0000-0000-0000-000000000000'::uuid)) STORED,
    calibrador_metodo text,
    cuota numeric,
    cuota_over numeric,
    cuota_under numeric,
    valor_real numeric,
    outcome_binario boolean,
    resuelto boolean DEFAULT false,
    timestamp_generacion timestamptz,
    timestamp_resolucion timestamptz,
    creado_en timestamptz,
    actualizado_en timestamptz,
    CONSTRAINT uq_prediccion_llave_natural UNIQUE
        (partido_id, mercado, lado, linea, origen, modelo_version_id, calibrador_id_efectivo)
);

CREATE TABLE predicciones_futbol (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    partido_id uuid,
    mercado text,
    origen text,
    linea numeric,
    fecha_partido timestamptz,
    prob_over numeric,
    prob_over_raw numeric,
    prob_over_calibrada numeric,
    prob_under_calibrada numeric,
    calibrador_id uuid,
    outcome_binario boolean,
    resuelto boolean,
    timestamp_generacion timestamptz,
    timestamp_resolucion timestamptz,
    creado_en timestamptz,
    actualizado_en timestamptz
);

CREATE TABLE modelo_versiones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version text,
    fecha_entrenamiento timestamptz,
    partidos_entrenamiento integer,
    cutoff_entrenamiento timestamptz
);

CREATE TABLE modelo_versiones_futbol (
    version text,
    fecha_entrenamiento timestamptz,
    partidos_entrenamiento integer,
    creado_en timestamptz
);

CREATE TABLE partidos_futbol (
    id uuid PRIMARY KEY,
    fecha_partido timestamptz,
    estado text,
    local_corners_2t integer,
    visitante_corners_2t integer,
    local_corners_total integer,
    visitante_corners_total integer,
    local_goles_total integer,
    visitante_goles_total integer,
    local_goles_1t integer,
    visitante_goles_1t integer,
    local_goles_2t integer,
    visitante_goles_2t integer
);

CREATE TABLE equipos (
    id uuid PRIMARY KEY,
    nombre text
);

CREATE TABLE partidos_baloncesto (
    id uuid PRIMARY KEY,
    fecha_partido timestamptz,
    temporada_id uuid,
    competicion_id uuid,
    equipo_local_id uuid,
    equipo_visitante_id uuid,
    tipo_partido text,
    local_q1 integer,
    local_q2 integer,
    local_q3 integer,
    local_q4 integer,
    local_total integer,
    valido boolean DEFAULT true,
    visitante_q1 integer,
    visitante_q2 integer,
    visitante_q3 integer,
    visitante_q4 integer,
    visitante_total integer
);

-- Replica a propósito el COALESCE legacy de Neon: los consumidores deben
-- ignorar p_efectiva/p_calibrada de la vista si falta calibrador_id.
CREATE VIEW vista_predicciones_para_calibracion AS
SELECT id, mercado, origen, fecha_partido, modelo_version_id,
       NULL::text AS equipo_local,
       NULL::text AS equipo_visitante,
       lado, linea,
       false AS linea_es_sintetica,
       p_raw, p_calibrada, calibrador_id,
       COALESCE(p_calibrada, p_raw) AS p_efectiva,
       outcome_binario,
       NULL::numeric AS media_predicha,
       NULL::numeric AS desviacion_predicha,
       valor_real,
       NULL::numeric AS intervalo_inferior,
       NULL::numeric AS intervalo_superior,
       NULL::integer AS nivel_intervalo
FROM predicciones_registradas;

CREATE TABLE apuestas_analizadas (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    deporte text NOT NULL,
    partido_id uuid NOT NULL,
    mercado text,
    lado text,
    linea numeric,
    probabilidad_sistema numeric,
    confianza text,
    estado text,
    resultado_outcome text,
    valor_real numeric,
    resultado_resumen text,
    creado_en timestamptz DEFAULT now(),
    actualizado_en timestamptz DEFAULT now(),
    decision_p_raw numeric,
    decision_p_calibrada numeric,
    decision_edge_real numeric,
    decision_score numeric,
    decision_sizing numeric,
    decision_valor_esperado numeric,
    decision_calibrador_id text,
    decision_modelo_version_id text,
    decision_fuente text,
    decision_devig_metodo text,
    decision_devig_overround numeric,
    decision_devig_p_mkt_fair numeric,
    decision_cuota numeric,
    decision_cuota_over numeric,
    decision_cuota_under numeric
);

CREATE SCHEMA analytics;
CREATE TABLE analytics.dq_alerts (
    id bigint,
    periodo date,
    domain text,
    alert_id text,
    severity text,
    component text,
    title text,
    condition_text text,
    incident_key text,
    status text,
    emitted boolean,
    repeat_count integer,
    trigger_value numeric,
    threshold_value numeric,
    warning_type text,
    warning_severity text,
    payload jsonb,
    created_at timestamptz,
    updated_at timestamptz,
    alerta_reincidente boolean,
    first_occurrence_at timestamptz
);
